- name: Build APK
        run: |
          # 初始化 gomobile
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          # 执行打包，确保路径 '.' 指向包含上面 main.go 的目录
          gomobile build -v -target=android -o cloudflare-test.apk .
